import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import {
  Xanh_Mono,
  Playfair_Display,
  Instrument_Serif,
} from 'next/font/google';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from '@/components/ui/sonner';

const playfairDisplayHeading = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-heading',
  weight: ['400', '500', '600', '700'],
});

const instrumentSans = Instrument_Serif({
  variable: '--font-serif',
  weight: ['400'],
  subsets: ['latin'],
});

const xanhMono = Xanh_Mono({
  variable: '--font-xanh-mono',
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'OnSPot',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        xanhMono.variable,
        instrumentSans.variable,
        playfairDisplayHeading.variable,
      )}
    >
      <body className="min-h-full bg-background flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster theme="system" />
        </ThemeProvider>
      </body>
    </html>
  );
}
