import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {
  Xanh_Mono,
  Playfair_Display,
  Instrument_Serif,
} from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import SessionProvider from "@/features/auth/provider/SessionProvider";

const playfairDisplayHeading = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
});

const instrumentSans = Instrument_Serif({
  variable: "--font-serif",
  weight: ["400"],
  subsets: ["latin"],
});

const xanhMono = Xanh_Mono({
  variable: "--font-xanh-mono",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MapaKain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={cn(
        "h-full",
        "antialiased",
        xanhMono.variable,
        instrumentSans.variable,
        playfairDisplayHeading.variable,
      )}
    >
      <body className="bg-background flex min-h-full flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>{children}</SessionProvider>
          <Toaster theme="system" />
        </ThemeProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/map-sw.js')
                    .then(reg => console.log('PWA Service Worker Registered!', reg.scope))
                    .catch(err => console.error('Service Worker Registry Failed:', err));
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
